WINDOW_WIDTH = window.innerWidth;
WINDOW_HEIGHT = window.innerHeight;

VIRTUAL_WIDTH = 256;
VIRTUAL_HEIGHT = 144;

SCALE_FACTOR_WIDTH = WINDOW_WIDTH / VIRTUAL_WIDTH;
SCALE_FACTOR_HEIGHT = WINDOW_HEIGHT / VIRTUAL_HEIGHT;

CAMERA_SPEED = 5;
JUMP_SPEED = 35;
GRAVITY = 1.5;